server:
  servlet:
    session.timeout: 15m

spring:
  application:
    name: comit-spring-jdbc
    
  security:
    user:
      name: admin
      password: 123
  
  datasource:
    url: jdbc:mysql://localhost:3306/mydbuser
    username: root
    password: root